# Development environment for SimEng
FROM ubuntu:20.04

# Install build dependencies
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      build-essential \
      cmake \
      git \
      llvm-9-dev \
      ninja-build \
      zlib1g-dev \
      python3 \
      wget \
      && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /workspace/SimEng

# Default command
CMD ["/bin/bash"]
